### PR TITLE
Adding an option to set file encoding

### PR DESCRIPTION
**Pull request by aletschhorn**
I deal with some legacy files that contain some special characters and are thus encoded in different unicode formats. It would thus be very convenient, to add a parameter 'encoding' to specify the corresponding encoding.

### CODE REVIEW

**Comment by virtuald** [comment]
Unfortunately we still support python 2.7. Can you fix this so that it works there too? Thanks!

**Comment by virtuald** [comment]
Would love to merge this, but the tests are still failing. Thanks!

**Comment by aletschhorn** [comment]
should now also work with python 2.7

**Comment by auscompgeek** [comment]
Doesn't `io.open` exist on Python 2? Seems reasonable to unconditionally use that instead, since it's an alias for `open` in Python 3.

**Comment by aletschhorn** [comment]
true!

**Comment by auscompgeek** [comment]
To be clear, I don't like the version check.

**Comment by virtuald** [comment]
Thanks for the contribution!

**Pull request merged**
